# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Our Friends Electric - Live Engagement Specialists
email: hello@ourfriendselectric.com.au
description: > # this means to ignore newlines until "baseurl:"
  We produce events. But we're more than just an event management company. 
  At our friends electric we build memorable and immersive brand experiences, 
  delivering high engagement for brands, big or small, 
  across the Asia Pacific region.
baseurl: "/_site" # the subpath of your site, e.g. /blog
url: "http://ofe.dev" # the base hostname & protocol for your site, e.g. http://example.com
facebook: https://www.facebook.com/yourfriendselectric
instagram: https://www.instagram.com/ourfriendselectric

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
  sass_dir: _sass
  style: compressed
  
collections:
  projects:
    output: false
    permalink: /:name
  
defaults:
  - type: 'projects'
    values:
      intro:
        client: Client Name
        project: Project Name
        description_html: >
         Description
      featured_image_path: 
      images: 
        - image_path: 
        - image_path: 
        - image_path: 
        - image_path: 
        - image_path: 